# Generated by Django 3.1.3 on 2020-12-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_lead_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_onwer',
            new_name='lead_owner',
        ),
    ]
