# Generated by Django 3.1.3 on 2020-12-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20201203_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_owner',
            new_name='owner',
        ),
    ]
